name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-latest ]
        node: [12, 14, 15, 16]
    steps:
      # Setup steps
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: yarn install

      # Run a build
      - name: Lint code
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build

  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Release it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
