name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-node-14:
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install deps
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build
